name = "wallet-secureproxy"
main = "src/index.js"
compatibility_date = "2024-01-01"
workers_dev = true

[vars]
CONTRACT_ADDRESS_EVM = "0x244C9881eA58DdaC4092e79e1723A0d090C9fB32"
CONTRACT_ADDRESS_SOL = "0x0A05F58CA8b31e9E007c840Bb8a00a63543eCEBC"

[[kv_namespaces]]
binding = "PROXY_CACHE"
id = "db8b3098bdc245a4ab8da2fcf63d0059"

# Secrets (set via .dev.vars locally or `wrangler secret put`):
# KEY_EVM
# KEY_SOL
